### ISSUE TITLE
Fatal error when acf field does not exists at a post.

### ISSUE THREAD

**Issue by marcoboom** [corcel/acf#13]
In AdvancedCustomFields.php the __get functions returns the get() method of the result of FieldFactory::make, but when the custom field not exists for a particuler post, the result of the FieldFactory will be null. So an exception will be thrown.

Better to change the return of the __get() method to:

```
 return $field ? $field->get() : null;
```

**Comment by jgrossi** [comment]
Hey @marcoboom thanks for reporting. Can you send a PR? Thanks!

**Comment by jgrossi** [comment]
Fixes #14. Thanks!
