### ISSUE TITLE
Funciona com Taxonomy? "Work with Taxonomy?"

### ISSUE THREAD

**Issue by blasterweb** [corcel/acf#2]
Consigo pegar o valor do campo ACF de uma Categoria (Taxonomy) ao invés do Post?

I can get the value of the ACF field of a Category (Taxonomy) instead of the Post?

**Comment by jgrossi** [comment]
Hi @blasterweb yes you can. You will receive an instance of `Corcel\Term` when using something like `$post->acf->my_field`.

**Comment by jgrossi** [comment]
@blasterweb you can alse use:

```php
$post->acf->term('field_name'); // or
$post->acf->taxonomy('field_name');
```
I'm gonna close this issue. So any question just let me know. 

JG
