### ISSUE TITLE
Custom post types 

### ISSUE THREAD

**Issue by cjke** [corcel/acf#5]
If resolving a field this way:

    $myPost = Movie::find(1);
    $myPost->acf->genre;  // not this version: $myPost->acf->text('genre');

results in an uncaught method on null exception because the constructed query looks like:

    "select * from `wp_posts` where `post_type` = ? and `post_name` = ?"
    ?1: moives // custom content type
    ?2: field_5852b438321e0  // custom field name

Which sets $field to null, which in turns slips through an "un-defaulted" switch statement in the field factory. Basically this results in ->setConnection on a null. The query above should be more like:

    "select * from `wp_posts` where `post_type` = 'acf-field' and `post_name` = "field_5852b438321e0"

Relevant snippets:
https://github.com/corcel/acf/blob/develop/src/FieldFactory.php#L58
https://github.com/corcel/acf/blob/develop/src/Field/BasicField.php#L117

Like issue #4 happy to PR it - just trying to think of a simple way to stub out the mysql without needing to stand up an entire server

**Comment by jgrossi** [comment]
@cjke hey I fixed that in the `0.1.4` version. If you still need that just update `corcel/acf` in composer file. I hope it helps you. JG

**Comment by cjke** [comment]
Dude you're killing it today - crushing issues. 

Quick question out of curiosity - how did you approach the concept of the same field key possibly existing in two groups? Is it required to pass in the group name as well?

**Comment by jgrossi** [comment]
:-) I don't think so but it should be tested. I did not write any unit test for that. We're using `_field_name` to get the field key to query in `wp_posts`, so think you'll have problem just for the same `post_id` using the same `field_name` for example. JG

**Comment by cjke** [comment]
Cool cool! Thanks for the awesome lib. We're releasing a biggish site in the next month which is using `React (frontend) <-> Laravel (backend) <-> Corcel <-> WP (content admin)` and Corcel has been an awesome addition. 
If you want to mark any issues in Corcel/Corcel or Corcel/Acf as "ideal first issue", I would be happy to pick some up.

**Comment by jgrossi** [comment]
@cjke thanks! And if you have any suggestion just let me know! Cheers! JG
