### ISSUE TITLE
Gallery field "undefined offset" error

### ISSUE THREAD

**Issue by omzy83** [corcel/acf#51]
I was uploading some images as part of a gallery field. During the upload there was a server error and the image did not save correctly to the DB. However it did upload the image and create the thumbnails.

When I loaded the page in the browser, I got an error: 

![image](https://user-images.githubusercontent.com/8927010/30186784-e0c57458-941e-11e7-808d-f20213887f7e.png)

Here is the function where the error is occurring:

![image](https://user-images.githubusercontent.com/8927010/30186817-ff44f494-941e-11e7-898d-da25f39d5742.png)

The problem is on line 40 we are assuming that `$attachment->ID` will always exist in `$metaDataValues` array, which in my case was not true. A simple `array_key_exists()` check is therefore necessary:

```
foreach ($attachments as $attachment) {
    if (array_key_exists($attachment->ID, $metaDataValues)) {
        $image = new Image($this->post);
        $image->fillFields($attachment);
        $image->fillMetadataFields($metaDataValues[$attachment->ID]);
        $this->images[] = $image;
    }
}
```

Please let me know if you will add this in or if you want me to send a PR.

**Comment by omzy83** [comment]
What do you think @jgrossi?

**Comment by jgrossi** [comment]
@omzy83 sorry about being MIA and thanks for sharing! go ahead and send a PR ;-) thanks

**Comment by omzy83** [comment]
@jgrossi PR is here: https://github.com/corcel/acf/pull/55
