### ISSUE TITLE
How to use the image

### ISSUE THREAD

**Issue by iteearmah** [corcel/acf#60]
Method Corcel\Acf\Field\Image::__toString() must return a string value (View:

**Comment by jgrossi** [comment]
@iteearmah Hi, first sorry about the late answer. These last weeks were busy. 

Can you provide more information about this error? When does it happen?

**Comment by maxkopych** [comment]
I had the same problem. To fix it you need to check if field exist
```
if($tool->acf->tool_icon){
	echo $tool->acf->tool_icon->url;
}
```
