### ISSUE TITLE
Not compatible with Corcel 4.0?

### ISSUE THREAD

**Issue by awcodes** [corcel/acf#89]
Any plans to update this package to work with Corcel 4.0 and Laravel 7?

Could really use it with a new site i'm working on. 

Thanks in advance.

**Comment by callumNE6** [comment]
Yes, I'm having the same problem when trying to install it. 

`Problem 1
    - Can only install one of: jgrossi/corcel[3.0.x-dev, v4.0.0].
    - Can only install one of: jgrossi/corcel[v4.0.0, 3.0.x-dev].
    - Can only install one of: jgrossi/corcel[3.0.x-dev, v4.0.0].
    - corcel/acf 2.0.0 requires jgrossi/corcel ^3.0 -> satisfiable by jgrossi/corcel[3.0.x-dev].
    - Installation request for corcel/acf ^2.0 -> satisfiable by corcel/acf[2.0.0].
    - Installation request for jgrossi/corcel (locked at v4.0.0, required as ^4.0) -> satisfiable by jgrossi/corcel[v4.0.0].`

**Comment by metapicture** [comment]
Yes, please update for compatibility with Corel 4 and Laravel 7. Thank you for the great packages!

**Comment by rpgroot** [comment]
i have same problem with laravel 7 and corel 4.0. please solve this problem.

**Comment by arzola** [comment]
@callumNE6 thank you man

**Comment by shanmugarajah25** [comment]
Yes, I'm also having the same problem when trying to install it.

C:\xampp\htdocs\Laravel\news> composer require corcel/acf
Using version ^2.0 for corcel/acf
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: jgrossi/corcel[3.0.x-dev, v4.0.0].
    - Can only install one of: jgrossi/corcel[v4.0.0, 3.0.x-dev].
    - Can only install one of: jgrossi/corcel[3.0.x-dev, v4.0.0].
    - corcel/acf 2.0.0 requires jgrossi/corcel ^3.0 -> satisfiable by jgrossi/corcel[3.0.x-dev].
    - Installation request for corcel/acf ^2.0 -> satisfiable by corcel/acf[2.0.0].
    - Installation request for jgrossi/corcel 4.0 -> satisfiable by jgrossi/corcel[v4.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by shanmugarajah25** [comment]
Yes, I'm having the same problem when trying to install it.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: jgrossi/corcel[3.0.x-dev, v4.0.0].
    - Can only install one of: jgrossi/corcel[v4.0.0, 3.0.x-dev].
    - Can only install one of: jgrossi/corcel[3.0.x-dev, v4.0.0].
    - corcel/acf 2.0.0 requires jgrossi/corcel ^3.0 -> satisfiable by jgrossi/corcel[3.0.x-dev].
    - Installation request for corcel/acf 2.0 -> satisfiable by corcel/acf[2.0.0].
    - Installation request for jgrossi/corcel (locked at v4.0.0, required as ^4.0) -> satisfiable by jgrossi/corcel[v4.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by jgrossi** [comment]
released new version on `3.0.0` that's compatible with Corcel 4.0.0+ 👍

**Comment by shanmugarajah25** [comment]
wowwww

awesome.
Thanks a lot. you are saving my time.




*Best Regards,*
*N.Shanmugarajah*
